language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install pylint"
  - "pip install -r requirements.txt"
script: ./run_tests.sh
matrix:
  fast_finish: true
